// Bundles src/symbols/<type>/{metadata.json,symbol.svg} into one ES module so the
// app works from file:// and in Node without runtime fetches.
import fs from 'node:fs';
import path from 'node:path';

const DIR = path.resolve('src/symbols');
const OUT = path.resolve('src/symbol-loader/library.generated.js');
const lib = {};
for (const type of fs.readdirSync(DIR).sort()) {
  const metaFile = path.join(DIR, type, 'metadata.json');
  if (!fs.existsSync(metaFile)) continue;
  const meta = JSON.parse(fs.readFileSync(metaFile, 'utf8'));
  if (meta.type !== type) throw new Error(`${metaFile}: type "${meta.type}" does not match folder "${type}"`);
  if (meta.svg) {
    const svg = fs.readFileSync(path.join(DIR, type, meta.svg), 'utf8');
    // Keep only the drawing; the renderer supplies its own transform/wrapper.
    meta.svgBody = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\n\s*/g, '');
  }
  lib[type] = meta;
}
fs.writeFileSync(OUT, `// Generated by scripts/build-symbols.mjs — do not edit.\nexport default ${JSON.stringify(lib)};\n`);
console.log(`bundled ${Object.keys(lib).length} symbols -> ${path.relative(process.cwd(), OUT)}`);
