// Scene -> standalone, portable SVG string (no external CSS, no <use>).
import { unionRect, boundsOf } from '../utils/geometry.js';

export const THEMES = {
  light: { ink: '#1b1b1f', wire: '#1b1b1f', muted: '#55565c', junction: '#1b1b1f', background: '#ffffff' },
  dark: { ink: '#e7e7ea', wire: '#e7e7ea', muted: '#a1a1aa', junction: '#e7e7ea', background: '#18181b' },
};
const FONT = 'Helvetica, Arial, sans-serif';

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const n = (v) => +(+v).toFixed(2);

export function sceneBounds(scene) {
  let b = null;
  for (const I of scene.instances.values()) {
    b = unionRect(b, I.body);
    b = unionRect(b, boundsOf(Object.values(I.pins)));
    for (const m of I.markers) b = unionRect(b, m.bbox);
    for (const l of I.labelsFinal || I.labels) b = unionRect(b, l.box);
  }
  for (const net of scene.routing.nets.values())
    for (const s of net.segments) b = unionRect(b, boundsOf([{ x: s.x1, y: s.y1 }, { x: s.x2, y: s.y2 }]));
  return b || { x: 0, y: 0, w: 200, h: 100 };
}

export function renderSVG(scene, opts = {}) {
  const th = THEMES[opts.theme] || THEMES.light;
  const pad = opts.padding ?? 30;
  const title = opts.showTitle !== false && scene.title ? String(scene.title) : '';
  const b = sceneBounds(scene);
  const titleH = title ? 30 : 0;
  const vx = Math.floor(b.x - pad), vy = Math.floor(b.y - pad - titleH);
  const vw = Math.ceil(b.w + 2 * pad), vh = Math.ceil(b.h + 2 * pad + titleH);
  const bg = opts.background === undefined ? th.background : opts.background;
  const out = [];
  out.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${vw}" height="${vh}" viewBox="${vx} ${vy} ${vw} ${vh}" font-family="${FONT}" data-generator="CircuitForge">`);
  out.push(`<title>${esc(title || 'Circuit schematic')}</title><desc>Generated by CircuitForge</desc>`);
  if (bg) out.push(`<rect x="${vx}" y="${vy}" width="${vw}" height="${vh}" fill="${bg}"/>`);
  if (title) out.push(`<text x="${n(b.x)}" y="${n(vy + pad + 12)}" font-size="14" font-weight="600" fill="${th.ink}">${esc(title)}</text>`);

  // wires
  out.push(`<g id="wires" fill="none" stroke="${th.wire}" stroke-width="1.6" stroke-linecap="square" stroke-linejoin="miter">`);
  const bridgeAt = new Map();
  if (opts.bridges) for (const c of scene.routing.crossings) {
    if (!bridgeAt.has(c.h)) bridgeAt.set(c.h, []);
    bridgeAt.get(c.h).push(c);
  }
  for (const net of scene.routing.nets.values()) {
    const hops = bridgeAt.get(net.id) || [];
    const d = net.paths.map((p) => pathD(p, hops)).join('');
    if (d) out.push(`<path data-net="${esc(net.id)}" d="${d}"/>`);
  }
  out.push('</g>');

  // components
  out.push(`<g id="components" color="${th.ink}">`);
  for (const I of scene.instances.values()) {
    const s = I.part.sym;
    const tf = `translate(${n(I.x)} ${n(I.y)})${I.rot ? ` rotate(${I.rot})` : ''}${I.mirror ? ' scale(-1 1)' : ''} translate(${n(-s.origin.x)} ${n(-s.origin.y)})`;
    const hit = opts.interactive ? `<rect class="cf-hit" x="${n(s.body.x - 4)}" y="${n(s.body.y - 4)}" width="${n(s.body.w + 8)}" height="${n(s.body.h + 8)}" fill="transparent" stroke="none"/>` : '';
    out.push(`<g id="${esc('part-' + I.id)}" class="cf-part" data-id="${esc(I.id)}" data-type="${esc(s.type)}" transform="${tf}">${hit}${s.svgBody}</g>`);
  }
  out.push('</g>');

  // rail markers
  out.push(`<g id="markers" color="${th.ink}" fill="none" stroke="${th.wire}" stroke-width="1.6">`);
  for (const I of scene.instances.values()) {
    for (const m of I.markers) {
      const parts = [];
      if (m.stubs.length) parts.push(`<path d="${m.stubs.map((st) => `M${n(st.x1)} ${n(st.y1)}L${n(st.x2)} ${n(st.y2)}`).join('')}" stroke-linecap="square"/>`);
      if (m.dot) parts.push(`<circle cx="${n(m.dot.x)}" cy="${n(m.dot.y)}" r="3.2" fill="${th.junction}" stroke="none"/>`);
      if (m.sym) {
        const t = m.t;
        parts.push(`<g transform="translate(${n(t.x)} ${n(t.y)})${t.rot ? ` rotate(${t.rot})` : ''} translate(${n(-t.ox)} ${n(-t.oy)})">${m.sym.svgBody}</g>`);
      }
      if (m.flag) {
        const pts = m.flag.map(([x, y]) => `${n(x)},${n(y)}`).join(' ');
        parts.push(m.box ? `<polyline points="${pts}"/><rect x="${n(m.box.x)}" y="${n(m.box.y)}" width="${n(m.box.w)}" height="${n(m.box.h)}" rx="2"/>` : `<polygon points="${pts}" stroke-linejoin="round"/>`);
      }
      if (m.text) parts.push(textEl(m.text, th.ink, 'normal'));
      out.push(`<g class="cf-marker" data-for="${esc(I.id)}" data-net="${esc(m.net)}">${parts.join('')}</g>`);
    }
  }
  out.push('</g>');

  // labels
  out.push(`<g id="labels" stroke="none">`);
  for (const I of scene.instances.values()) {
    const ls = I.labelsFinal || I.labels;
    if (!ls.length) continue;
    out.push(`<g class="cf-labels" data-for="${esc(I.id)}">${ls.map((l) => textEl(l, l.cls === 'value' ? th.muted : th.ink, l.cls === 'ref' ? '600' : 'normal')).join('')}</g>`);
  }
  out.push('</g>');

  // junctions
  out.push(`<g id="junctions" fill="${th.junction}" stroke="none">`);
  for (const j of scene.routing.junctions) out.push(`<circle cx="${n(j.x)}" cy="${n(j.y)}" r="3.2"/>`);
  out.push('</g>');
  out.push('</svg>');
  return { svg: out.join('\n'), width: vw, height: vh, viewBox: { x: vx, y: vy, w: vw, h: vh } };
}

function textEl(l, fill, weight) {
  return `<text x="${n(l.x)}" y="${n(l.y)}" font-size="${l.size}" text-anchor="${l.anchor}" fill="${fill}"${weight !== 'normal' ? ` font-weight="${weight}"` : ''}>${esc(l.text)}</text>`;
}

const R = 4.5; // bridge radius

function pathD(pts, hops) {
  if (pts.length < 2) return '';
  let d = `M${n(pts[0].x)} ${n(pts[0].y)}`;
  for (let i = 1; i < pts.length; i++) {
    const a = pts[i - 1], b = pts[i];
    if (a.y === b.y && hops.length) {
      const dir = b.x > a.x ? 1 : -1;
      const xs = hops.filter((h) => h.y === a.y && (h.x - a.x) * dir > R && (b.x - h.x) * dir > R)
        .map((h) => h.x).sort((p, q) => (p - q) * dir);
      for (const x of xs) {
        d += `H${n(x - dir * R)}a${R} ${R} 0 0 ${dir > 0 ? 1 : 0} ${n(dir * 2 * R)} 0`;
      }
    }
    d += a.x === b.x ? `V${n(b.y)}` : a.y === b.y ? `H${n(b.x)}` : `L${n(b.x)} ${n(b.y)}`;
  }
  return d;
}
